---
- name: Disable root login and password authentication
  hosts: nodes
  become: yes
  tasks:
    - name: Backup the original sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: yes

    - name: Configure SSH security settings
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
        - { regexp: '^UsePAM', line: 'UsePAM no' }

    - name: Set correct permissions on sshd_config
      file:
        path: /etc/ssh/sshd_config
        mode: '0600'
        owner: root
        group: root

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
